In [2]:
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from bs4 import BeautifulSoup
import pandas as pd

In [75]:
def initialize_browser(pag=None, headless=True):

    service = Service(ChromeDriverManager().install())
    options = Options()
    options.add_argument('--start-maximized')

    if headless:
        options.add_argument('--headless')

    browser = webdriver.Chrome(service=service, options=options)
    browser.implicitly_wait(10)

    if pag == None:
        browser.get('https://www.metacritic.com/browse/game/')
    else:
        browser.get(f'https://www.metacritic.com/browse/game/?releaseYearMin=1958&releaseYearMax=2024&page={pag}')

    return browser

In [85]:
browser = initialize_browser(headless=False)

soup = BeautifulSoup(browser.page_source, 'html.parser')

n_pag = int(soup.find_all('span', attrs={'class':'c-navigationPagination_itemButtonContent'})[-2].text)

games_block = soup.find('div', attrs={'class':'c-productListings'})

names_scrap = games_block.select("h3[class='c-finderProductCard_titleHeading'] > span")
dates_scrap = games_block.select("div[class='c-finderProductCard_meta'] > span[class='u-text-uppercase']")
scores_scrap = games_block.select("span[class='c-finderProductCard_metaItem c-finderProductCard_score'] > div > div > span")

browser.quit()

In [63]:
names=list()
for name in names_scrap[1::2]:
    names.append(name.text)

dates=list()
for date in dates_scrap:
    dates.append(date.text.strip())

scores=list()
for score in scores_scrap:
    scores.append(int(score.text))

In [64]:
games={'names':names,'dates':dates,'scores':scores}

In [66]:
pd.DataFrame(data=games)

                                      names         dates scores
0      The Legend of Zelda: Ocarina of Time  Nov 23, 1998     99
1                               SoulCalibur   Sep 8, 1999     98
2                       Grand Theft Auto IV  Apr 29, 2008     98
3                        Super Mario Galaxy  Nov 12, 2007     97
4                      Super Mario Galaxy 2  May 23, 2010     97
5   The Legend of Zelda: Breath of the Wild   Mar 3, 2017     97
6                  Tony Hawk's Pro Skater 3  Oct 30, 2001     97
7                       Perfect Dark (2000)  May 22, 2000     97
8                     Red Dead Redemption 2  Oct 26, 2018     97
9                        Grand Theft Auto V  Nov 18, 2014     97
10                            Metroid Prime  Nov 17, 2002     97
11                     Grand Theft Auto III  Oct 22, 2001     97
12                      Super Mario Odyssey  Oct 27, 2017     97
13                     Halo: Combat Evolved  Nov 15, 2001     97
14                                  NFL 2K1   Sep 7, 2000     97
15                              Half-Life 2  Nov 16, 2004     96
16                                 BioShock  Aug 21, 2007     96
17                            GoldenEye 007  Aug 25, 1997     96
18               Uncharted 2: Among Thieves  Oct 13, 2009     96
19                   Resident Evil 4 (2005)  Jan 11, 2005     96
20                          Baldur's Gate 3   Aug 3, 2023     96
21                           The Orange Box  Oct 10, 2007     96
22                                 Tekken 3  Apr 29, 1998     96
23                            Mass Effect 2  Jan 26, 2010     96

In [88]:
browser = initialize_browser(headless=False)

soup = BeautifulSoup(browser.page_source, 'html.parser')

n_pag = int(soup.find_all('span', attrs={'class':'c-navigationPagination_itemButtonContent'})[-2].text)

names=list()
dates=list()
scores=list()

for pag in range(1,5):

    browser.get(f'https://www.metacritic.com/browse/game/?releaseYearMin=1958&releaseYearMax=2024&page={pag}')

    games_block = soup.find('div', attrs={'class':'c-productListings'})

    names_scrap = games_block.select("h3[class='c-finderProductCard_titleHeading'] > span")
    dates_scrap = games_block.select("div[class='c-finderProductCard_meta'] > span[class='u-text-uppercase']")
    scores_scrap = games_block.select("span[class='c-finderProductCard_metaItem c-finderProductCard_score'] > div > div > span")

    for name in names_scrap[1::2]:
        names.append(name.text)
    
    for date in dates_scrap:
        dates.append(date.text.strip())
    
    for score in scores_scrap:
        scores.append(int(score.text))

browser.quit()

In [94]:
print(len(names))

72

In [95]:
n_pag

553

In [90]:
games={'names':names,'dates':dates,'scores':scores}
pd.DataFrame(data=games)

                                   names         dates  scores
0   The Legend of Zelda: Ocarina of Time  Nov 23, 1998      99
1                            SoulCalibur   Sep 8, 1999      98
2                    Grand Theft Auto IV  Apr 29, 2008      98
3                     Super Mario Galaxy  Nov 12, 2007      97
4                   Super Mario Galaxy 2  May 23, 2010      97
..                                   ...           ...     ...
67                Resident Evil 4 (2005)  Jan 11, 2005      96
68                       Baldur's Gate 3   Aug 3, 2023      96
69                        The Orange Box  Oct 10, 2007      96
70                              Tekken 3  Apr 29, 1998      96
71                         Mass Effect 2  Jan 26, 2010      96

[72 rows x 3 columns]